library/errata_tool_product.py
module_utils/common_errata_tool.py
tests/test_common_errata_tool.py
tests/test_errata_tool_product.py

The `errata_tool_product` module is the only module that needs this list, so it makes sense to store this directly in the `errata_tool_product` module instead of storing it in `common_errata_tool`.

product: move BUGZILLA_STATES to product module

---

tests/test_errata_tool_product.py

This was a bad copy-and-paste from another test.

tests: fix test class name for get_product

---

README.rst

The GET REST API returns `program_manager`'s `login_name`. Users must specify the `login_name` so that these values line up.

README: program_manager must be a login_name

---

tests/conftest.py

If a developer has set `ERRATA_TOOL_URL` or `ERRATA_TOOL_AUTH`, ignore those during the tests.

tests: ignore ERRATA_TOOL_URL and ERRATA_TOOL_AUTH vars

---

module_utils/common_errata_tool.py
tests/test_common_errata_tool.py

We will use this in the upcoming `errata_tool_cdn_repo` module, like:
```
DELETE /api/v1/cdn_repo_package_tags/{id}
```

common: add Client.delete() method

---

module_utils/common_errata_tool.py

The ET Apache server has many problems with mutual authentication.  Disable all verifications of the GSSAPI mutual auth responses.

common: disable mutual authentication

---

.mergify.yml

I migrated errata-tool-ansible from travis-ci.org to travis-ci.com today, because the older travis-ci.org system used GitHub's legacy services integration, and today I encountered a problem where travis-ci.org fails to report PR build status back to GitHub.
After that transition to Travis CI's new "Application", the status reports names are different now. Mergify needs to respect the newer status report names.

mergify: update for Travis CI Application transition

---

library/errata_tool_release.py

https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec says "When not specified, the default value is `None`"
We can omit "`default=None`" and rely on the default AnsibleModule behavior here.

release: remove "default=None" from argspec

---

tox.ini

We were already testing py37 in Travis CI. Update tox.ini to match what we are testing in Travis CI, so that developers will easily run the same test matrix locally.

tox.ini: add py37

---

.stickler.yml

We mainly care about Python 3 nowdays, and Stickler CI defaults to Python 2.
Run the Stickler CI flake8 tests within a Python 3 environment.

.stickler.yml: run flake8 with Python 3

---

library/errata_tool_variant.py

We were getting HTTP 403 errors in stage with our system account, and we suspect this is because we're always trying to set the CPE text for a variant every time we create or edit it.
Make the "cpe" parameter optional, and if it is "null" (the default), do not send a cpe value to the ET server.

variant: make cpe text optional

---

library/errata_tool_variant.py

When we receive an HTTP 403 error from the HTML form, there is very little information about what went wrong.
Return the entire HTML page. This will bloat the logs, but it will provide us more information.
A future improvement would be to look at a log file where we hit this code path, and then determine exactly what HTML values (error message) to screen-scrape here, and then only raise that exact error message, like we do elsewhere in `handle_form_errors()`.
A better improvement would be to have a proper REST API for variants (ERRATA-9718) so we have an official, documented way to handle errors.

variant: raise response.text contents on 403 error

---

library/errata_tool_variant.py

If we fail to screen-scrape the exact errors in `scrape_error_explanation()`, we have no more information about what went wrong.
Raise the entire HTML body so we have some clue about what to do next.

variant: handle scrape_error_explanation() failures

---

library/errata_tool_product_version.py
library/errata_tool_variant.py

1) The push targets must be set on the parent object (product or product_version) first. Mention this in the docs.
2) A variant does not inherit push targets from the parent if they are unset. Correct this erronous statement.
3) "ftp" is not a valid push target for variants. Remove this from the docs.

doc: improve docs for product_version and variant push_targets

---

library/errata_tool_variant.py
tests/test_errata_tool_variant.py

Fix the failure to scrape the error messages in `errata_tool_variant.py`'s
`scrape_error_explanation()` method.
Add a unit test to verify the correct behavior.

variant: update scrape_error_explanation() method

---

library/errata_tool_release.py

1) `ship_date` is only required for `QuarterlyUpdate` releases. Mark this field as optional in Ansible.
2) The following are irrelevant for `Async` and `Zstream` releases:
- `allow_shadow`
- `allow_blocker`
- `allow_exception`
- `allow_pkg_dupes`
- `supports_component_acl`
- `limit_bugs_by_product`
Mark these fields as optional in Ansible.

release: make several fields optional

---

library/errata_tool_release.py

If we do not send `product_version_ids` in every PUT request, the ET server will reset the product versions to an empty list.
We can revert this change when the fix for ERRATA-9867 is deployed to production.

release: send product_version_ids in every PUT request

---

library/errata_tool_variant.py
tests/test_errata_tool_variant.py

When we get an HTTP 403 error response from submitting the "variant" HTML form, we need to screen-scrape a slightly different HTML `<div>` in order to determine the exact error message.

variant: scrape error-text div for messages

---

library/errata_tool_user.py
tests/test_errata_tool_user.py

In some cases, we can get an HTTP 404 error for a user account.
When this happens, it's not clear if the user does not exist or if the server failed to process the user's esoteric login_name.
When we get a 404, try screen-scraping the "Find User" form to find the user ID before giving up.

user: handle 404 errors

---

library/errata_tool_variant.py

In the case where no CPE is passed via playbook, the diff prints out
something like:
"changing cpe from cpe:/a:redhat:cpe:stuff::el to None"
This makes it look like the CPE will be overwritten rather
than just being skipped.

Omit CPE diff printouts if no CPE included

---

library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

Prior to this change, if a CDN repository had no packages set, the HTTP API would not return a "packages" key under "relationships".  The `get_cdn_repo()` method would raise a `KeyError` because we unconditionally queried `"packages"`.
Gracefully handle the case where the API does not return any packages data. `get_cdn_repo()` will return an empty list of `package_names`.
Fixes: #38

cdn_repo: gracefully handle no packages for a repo

---

library/errata_tool_cdn_repo.py

Update the documentation to describe how to restrict a package's tag to a single variant.
Fixes: #39

cdn_repo: document how to restrict tags to variants

---

README.rst

We do want to publish this as an Ansible collection. Remove the speculative "maybe".
Remove the link to the upstream Ansible Galaxy issue, because this is resolved now.

README: update collection TODO item

---

library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

CDN repositories that are not `content_type: Docker` should not have packages set.
Fixes: #44

cdn_repo: make packages parameter optional

---

library/errata_tool_release.py

Fixes flake8 errors:
```
F401 'lxml.html' imported but unused
F401 're' imported but unused
```

release: remove unused lxml.html and re imports

---

README.rst
library/errata_tool_cdn_repo.py
library/errata_tool_product.py
library/errata_tool_product_version.py
library/errata_tool_release.py
library/errata_tool_user.py
library/errata_tool_variant.py

Document that we depend on `requests-gssapi` and `lxml` in each module's inline docs. I'm adding `lxml` to every module's documentation, even though every module does not use `lxml`, because `common_errata_tool` requires it.
Document how to install `requests-gssapi` and `lxml` in the `README`.
Fixes: #47

document Python library dependencies

---

library/errata_tool_cdn_repo.py

Fix a bad copy & paste for the `cdn_repo_data` parameter docstring.

cdn_repo: fix get_cdn_repo() docstring for cdn_repo_data

---

library/errata_tool_product.py

`ansible-doc` raises an error when we do not set a description for every option.

product: add description for text_only_advisories_require_dists

---

library/errata_tool_release.py

ansible-doc fails to parse the inline documentation for this module if we do not specify a simple boolean "true" or "false" here.
Simply remove the line, because the value is required in the QuarterlyUpdate case, but not in the ZStream or Async cases.

release: rm non-bool value in ship_date docs

---

library/errata_tool_variant.py

ansible-doc raises an error when we do not set a description for every option.

variant: add descriptions for "enabled" and "buildroot" options

---

library/errata_tool_cdn_repo.py
library/errata_tool_product.py
library/errata_tool_product_version.py
library/errata_tool_release.py
library/errata_tool_variant.py

Prior to this change, ansible-doc failed to parse the inline docs for the modules. Edit or quote lines that use ":" so that ansible-doc can parse these.

fix YAML syntax in documentation

---

galaxy.yml

Ansible Galaxy fails to vaildate the tag "errata-tool". Use a general "packaging" tag instead.

galaxy: replace "errata-tool" tag with "packaging"

---

build-collection

To be compatible with the 2.9 version of `ansible-galaxy`, trim our collection version number to be the simple `0.0.X` format.
Ansible 2.10's `ansible-galaxy` utility respects the full SemVer specification, so this is not an issue on Ansible 2.10+. We can revert this change when we're ready to drop Ansible 2.9 support.

Ansible 2.9's `ansible-galaxy` utility is strict about what versions it accepts. It only accepts versions that match `StrictVersion.version_re`.

---

library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

If a package in a repository has zero tags, `get_package_tags()` will not return any key for that package name at all. The reason is that the `/api/v1/cdn_repo_package_tags` API endpoint does not return any entries for packages with zero tags.
Prior to this change, the `ensure_packages_tags()` method could raise a `KeyError` when we try to compare the `current_tags` for a package with the `desired_tags`, because `current_tags` has no key for this `package_name`.
Update `ensure_package_tags()` to handle the missing `package_name` keys in the `current_tags` data we obtain from `get_package_tags()`.
Update the code comments to reflect the ET's behavior here, and add a unit test that verifies the ability to add a tag to a package that starts with zero tags.
Fixes: #72

errata_tool_cdn_repo: handle reading pkgs with no tags

---

library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

The Errata Tool validates new tag names with a regular expression, and sometimes it's hard to understand exactly which tag name string failed this validation.
Raise the entire request body (which includes the offending tag name) as well as the server error message.

cdn_repo: log add_package_tag() request JSON on error

---

README.rst

The CDN repository tags are tricky to get right in Ansible. Add more instructions to the README about this.

improve documentation for escaping CDN repo tag

---

library/errata_tool_user.py

When there is no organization defined then it was detected change since
default org 'Engineering' does not match with None.
Fixed by not comparing organization when it's not in params.
Fixes #58

Fix issue with missing organization for user

---

library/errata_tool_cdn_repo.py
library/errata_tool_product.py
library/errata_tool_product_version.py
library/errata_tool_release.py
library/errata_tool_user.py
library/errata_tool_variant.py
module_utils/common_errata_tool.py
tests/test_common_errata_tool.py
tests/test_errata_tool_cdn_repo.py
tests/test_errata_tool_user.py

The new variants REST API is live in production now, so ERRATA-9717 is resolved. I switched to this new API in commit 55a7133414f22a9ac26cf0dc2f29e0da0e9a4c45, but I forgot to drop the comments that still refer to that ticket.
All the old "ERRATA" tickets that are still open have moved to the CLOUDWF project in Jira. Update the comments to use the new ticket keys so they are easier to find and discuss.

update Jira ticket references

---

library/errata_tool_product.py

The parameter is named "`bugzilla_product_name`". Update the inline docs to reflect this.

product: fix bugzilla_product_name parameter docs

---

README.rst

This value should be capitalized. The ET automatically transforms it to upper-case server-side, however, this will print a "changed" message on subsequent Ansible runs.

README: upper-case example rhel_release_name

---

library/errata_tool_product.py

Update the inline docs to the correct parameter name: "`valid_bug_states`". Update the description to specify that this only applies to Bugzilla bugs.
Prior to this change, if a user omitted "`valid_bug_states`", the module would crash because it would try to iterate over None. Update the default value to be a list so we do not crash.
When we send an empty `valid_bug_states` list to the server, the server defaults to a value of "MODIFIED,VERIFIED". Duplicate this default behavior here. This will remove the spurious change message from `stdout_lines` when users omit this parameter. Also check mode correctly displays what would change when users omit the value.
Fixes: #77

product: valid_bug_states fixes

---

library/errata_tool_release.py

If we read a release with `get_release()` and `program_manager` is `null`, we crash when we try to read `login_name`.
Check for this condition and set program_manager to None, like we do with `state_machine_rule_set`.
Fixes: #89

release: handle null program manager

---

README.rst

`yamllint` complains when we don't indent these lists. Provide users with examples that will satisfy `yamllint`.

README: indent lists in YAML examples

---

tox.ini

Prior to this change, the flake8 tox env failed, because I misspelled the `library` directory.

tox: fix library path typo for flake8 env

---

tests/test_errata_tool_cdn_repo.py

Remove the comment about `check_mode=True`, because the tests in this class exercise both `True` and `False` values for `check_mode`.

cdn_repos: fix TestEnsureCdnRepo docstring

---

library/errata_tool_user.py
tests/test_errata_tool_user.py

If the playbook author specifies no list of roles, do not reset the roles.
Related: #80

user: do not reset roles if unspecified

---

library/errata_tool_user.py
tests/test_errata_tool_user.py

This pull request changes the behavior of the `errata_tool_user` module in the following ways:
- Do not accidentally reset `receives_mail` to `false` (CLOUDWF-2817)
- Do not modify an existing user's email address if the playbook author omits the `email_address` parameter.
Fixes: #80

user: receives_mail and email_address parameter improvements

---

library/errata_tool_variant.py

The ET does not permit users to set the "ftp" or "altsrc" Push Targets on variants. Add this information to the inline docs, and remove "altsrc" from the documented list of possible choices.
Fixes: #104

variant: document allowable_by_variant push targets

---

library/errata_tool_release.py

The `program_manager` parameter should be the user account `login_name`, which may or may not be the Kerberos principal. Update the description for the `program_manager` field to reflect this, and give an example `login_name` with a lowercase "@redhat.com" suffix.

release: update doc description for program_manager

---

library/errata_tool_release.py

This parameter behaves a little differently than other parameters when a playbook author omits it. Document what happens when omitting it.
Other parameters do not override values when unspecified, so this behavior is a little surprising. See `default_docs_reviewer` in `errata_tool_product.py` for an example of a parameter that behaves in the opposite way.
I'm preserving this behavior and documenting it instead of changing this now. My reason is that I want to be able to set rules back to "null" on releases. Generally speaking, it adds a lot of complexity to have per-release rules that override per-product rules. I'm thinking we should steer playbook authors toward simplifying their configurations instead of making them more complex.
Maybe in the future we can revisit this decision. The …

release: document default behavior for state_machine_rule_set

---

tests/test_errata_tool_variant.py

The `edit_variant()` method does not make any GET requests, so we do not need to register a fake GET response. (This was likely a bad copy-and-paste from another test.)

tests: remove useless register_uri() from test_edit_variant

---

library/errata_tool_product_version.py

Nothing in the `errata_tool_product_version` module uses this class. It was a bad copy-and-paste from other modules. We can simply remove it.

product_version: remove unused InvalidInputError class

---

.mergify.yml

The new GitHub Action integration tests have been working for a while.  Gate Mergify's activity on the integration tests. With this change, Mergify will only auto-merge PRs if the integration tests pass.

mergify: require integration tests to pass

---

.mergify.yml
.travis.yml

Fix the errors that yamllint finds in `.travis.yml` and `.mergify.yml`.

fix yamllint errors in .travis.yml and .mergify.yml

---

library/errata_tool_release.py

Use the indefinite article "a" to match up "a QuarterlyUpdate" in the previous sentence.
"ZStream" is not the right capitalization. Use "Zstream".

release: fix grammer in ship_date description

---

tests/fixtures/rhceph-4.0.release.json
tests/test_errata_tool_release.py

Add unit tests for the core get, create, and edit methods in `errata_tool_release.py`.

release: test get, create, edit methods

---

library/errata_tool_release.py
tests/test_errata_tool_release.py

Prior to this change, if we managed a release with a null product, we crashed in two places:
1) `get_release()` when we try to read the `short_name` key on a `None` value
2) `api_data()` when we call `get_product_id()` with `product_name=None`
Check for `None` and avoid these crashes.
Fixes: #121

release: handle null product

---

.travis.yml
tox.ini

RHEL 7 has py36
RHEL 8 has py36 and py38
Fedora 32 has py38
Fedora 33 will have py39
I don't care about py37 at this point. Drop it from our Tox and Travis CI configuration to save time and energy.

tests: remove py37 from tox and travis ci

---

README.rst

Link to our collection entry on Ansible Galaxy, and describe how users can install the latest collection with the `ansible-galaxy` CLI.

README: document Ansible Galaxy installation

---

tests/test_errata_tool_release.py

Check for the final HTTP request in the history, rather than counting the requests and hard-coding the length.
This makes this test more resiliant against future design changes. For example, CLOUDWF-298 is an RFE to allow setting parameters by name instead of ID number, which would reduce the number of HTTP GET calls we make to look up ID numbers, breaking the hard-coded history index numbers.
This change also makes it easier to understand the intention of the unit test: we only care about "the final" HTTP request, rather than "the fifth" request.

release: improve history checking in test_create_release()

---

tests/test_errata_tool_release.py

Clean up the `errata_tool_release` module unit tests in two ways:
1. Remove a duplicate key in the `params()` test fixture.
2. Remove unused `params` fixtures from `TestEditRelease`.

release: clean up unit test fixtures

---

library/errata_tool_release.py
tests/test_errata_tool_release.py

Prior to this change, if a user set a value for `state_machine_rule_set` for an `errata_tool_release`, we crashed with an error because the `WorkflowRules` class does not exist. This came from a very old version of the code, and I never tested this code path again after I wrote `WorkflowRulesScraper`. The correct class to use now is `WorkflowRulesScraper`.
Use the `WorkflowRulesScraper` class to scrape the `state_machine_rule_set` ID number, just like we do in the `errata_tool_product` module.
The old code called `upper()` on the `state_machine_rule_set` string. Remove this line, because this parameter is actually case-sensitive.  (`WorkflowRulesScraper` uses the exact rule names.)
Remove the incorrect choices from the inline documentation and add the correct choices.
Add a unit test that …

release: fix state_machine_rule_set parameter

---

tests/test_errata_tool_release.py

Add a unit test that tries to create a release with no product and asserts that we're sending the expected JSON.

tests: test create_release() with no product Async release

---

tests/integration/errata_tool_variant/create-2.yml

We don't specify the `cpe` parameter in the `errata_tool_variant` task.  Ensure that the default value is the one we expect.

variant: assert null cpe in layered product integration test

---

library/errata_tool_product.py

Correct the inline documentation for the `ftp_path` and `ftp_subdir` parameters.

product: fix inline docs for ftp_path and ftp_subdir

---

library/errata_tool_cdn_repo.py
library/errata_tool_product.py
library/errata_tool_product_version.py
library/errata_tool_release.py
library/errata_tool_user.py
library/errata_tool_variant.py
tests/test_errata_tool_release.py

Make `null` mean "the server will choose a value for new resources, or not edit an existing resource's value".
Some modules had a couple `if parameter is None: ...` conditionals to specially handle individual null values. Drop these special cases since we're generalizing this convention across all modules and parameters now.
This is a prerequisite to resolving #129. After we merge this, we need to review each parameter with a "default" value, figure out how we can default it to "None", and then document what the server does when we create a resource without that parameter.

do not send "null" values to ET API

---

library/errata_tool_release.py

Prior to this change, if a user specified no `blocker_flags` parameter, we passed an empty list to the ET when creating or editing a variant.
A default empty list is not good for two reasons:
1) If a playbook author omits this setting, Ansible will surprisingly reset the values on the server.
2) It's not possible to set an empty list for `Zstream` releases (or `QuarterlyUpdate` releases with `supports_component_acl`: `true`). The server error is: `{"blocker_flags": ["Need a release version flag"]}`
Default `blocker_flags` to `null` (and we do not send the `blocker_flags` value to the API at all if it is `null`).
Related: #129

release: improve blocker_flags default behavior

---

tests/test_common_errata_tool.py

Use pytest's `paramterize` method to run individual tests for each test case.
This makes the output of `pytest -v` clearer. It makes it easier to see the exact test that failed. This also causes pytest to run all the tests, rather than bailing out after the first AssertionError.

common: use pytest parametrization for TestWorkflowRulesScraper

---

tests/fixtures/products_new.html
tests/test_common_errata_tool.py

Add unit test coverage for the `PushTargetScraper` class.
The `products_new.html` fixture file is a manually-sanitized version of the ET HTML page, just enough so that we can pass it through the scraper.

common: add unit tests for PushTargetScraper

---

README.rst

Use preformatted text to highlight the `errata_tool_request` module name. This makes this paragraph easier to read and understand.

README: preformatted text for errata_tool_request module

---

module_utils/common_errata_tool.py

`PushTargetScraper` is a full class now, not just a simple method. Update the docstring comment to reflect the fact that we will delete the entire class once we can edit Push Targets by name. This change makes it easier to understand this sentence.

common: fix comment about need for PushTargetScraper

---

library/errata_tool_product_version.py

Shorten and break up the code so that the lines wrap at 80 characters to satisfy linters.

product_version: wrap rhel_release_name assignment at 80 characters

---

tox.ini

Update the tox configuration for the "flake8" environment so that we do not hide any warnings or errors.
This will cause `tox -e flake8` to fail on line length problems and anything else.

tox: report all flake8 warnings and errors

---

module_utils/common_errata_tool.py

Shorten the code so that the line wraps at 80 characters to satisfy linters.

common: wrap push target description error at 80 characters

---

tox.ini

Prior to this change, `tox -e flake8` would skip checking the `module_utils` directory. This meant that we did not report flake8 issues in `common_errata_tool.py`.
Update the `flake8` command to run against both the `library` and `module_utils` directories. With this change, we will lint the full Ansible module codebase (ignoring tests).

tox: run flake8 against module_utils

---

tests/integration/errata_tool_release/blocker-flags-1.yml
tests/integration/errata_tool_release/create-1.yml
tests/integration/errata_tool_release/create-2.yml
tests/integration/errata_tool_release/main.yml
tests/integration/errata_tool_release/pelc-product-version-name-1.yml
tests/integration/errata_tool_release/product-versions-1.yml
tests/integration/errata_tool_release/state-machine-rule-set-1.yml

Add a series of integration tests for `errata_tool_release`.
There are two general "create" tests, and some tests that exercise setting + updating + un-setting some attributes (`blocker_flags`, `pelc_product_version_name`, `state_machine_rule_set`, `product_versions`)

release: add integration tests

---

library/errata_tool_release.py
module_utils/common_errata_tool.py
tests/test_common_errata_tool.py

AnsibleModule's `argument_spec` permits a "choices" setting for parameters. This setting defines the options that a playbook author can choose. Ansible will print an error message for all other options.
Use this built-in functionality instead of implementing our own in the `validate_params()` method.

release: use choices for "type" validation

---

library/errata_tool_release.py

The code for `changing_product_versions` was overly complex. Simplify it by using a list comprehension to determine all the keys we're changing, and then search that list.

release: simplify product_versions key search

---

module_utils/common_errata_tool.py

Gerrit 193086 is resolved. The dev ET instances' push target names align with the names in staging and production. We can drop this old code now.
Fixes: #142

common: remove unused "Docker stage" push target

---

tests/integration/errata_tool_cdn_repo/create-1.yml
tests/integration/errata_tool_cdn_repo/create-2.yml

This was a bad copy-and-paste from another test.

cdn_repo: fix set_fact name in integration tests

---

library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

Sometimes this API endpoint returns an "errors" key instead of an "error" key. This leads to KeyErrors. (For example, I hit this when I tried to add a second variant to a CDN repo that already had a variant from that same Product Version).
Since we don't have a robust error-handling method, in order to keep this code simple, just raise the entire JSON response, since it's usually pretty small.

cdn_repo: report entire JSON response on edit errors

---

library/errata_tool_cdn_repo.py

Users cannot modify `release_type` or `content_type` for existing CDN repos.
Users should not set `use_for_tps` on Docker CDN repos.
Document these restrictions in the inline Ansible module documentation.
Fixes: #171

cdn_repo: document restrictions on parameters

---

library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

The REST API allows users to set `use_for_tps` on Docker repos, but the HTML UI does not allow it. Until the ET server prevents this misconfiguration, guard against this client-side in the Ansible module.

cdn_repo: prevent use_for_tps with Docker repos

---

library/errata_tool_cdn_repo.py

Give another example of configuring an RPM repo, this time for s390x sources.

cdn_repo: add example for sources RPMs / s390x

---

library/errata_tool_product_version.py
tests/test_errata_tool_product_version.py
tox.ini

This will make debugging easier since before this commit, it would just
show an ugly traceback with near the end of it:
RuntimeError: <Response [500]>

Expose the response text of a 500 error when configuring a product version

---

library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

If the response from Errata Tool is an error on the api/v1/cdn_repos
API endpoint, show the response text if the JSON does not have the
error key.
This prevents errors such as the following in Ansible:
...
line 307, in create_cdn_repo
KeyError: 'error'
...

Show the response text if the cdn_repos failure does not have an error message

---

.github/workflows/tests.yml
build-collection

When a GitHub Action runner checks out a pull request for testing, it checks out GitHub's magic "merge" ref. For example:
```
git checkout --progress --force refs/remotes/pull/192/merge
```
This puts the repository into a detached HEAD state. This means that we cannot search `HEAD` for `--max-parents=0`, because Git will simply return the sha we've checked out. This problem means that `COMMIT_COUNT` is always `-1` for pull requests and VERSION is always `0.0.-1`.
GitHub Action runners have a `GITHUB_BASE_REF` environment variable with the name of a pull request base branch. If that is defined, use that to discover the root commit of the base branch. This fixes the `COMMIT_COUNT` calculation for pull requests.
Fixes: #193

build-collection: fix VERSION for pull requests

---

.github/workflows/tests.yml

When this action runs on a master branch update, the fetch for master will fail here. Treat this as non-fatal.

github: make master fetch non-fatal

---

tox.ini

requests-mock 1.9.0 runs `urlparse.quote()` on paths, and this breaks matching paths like `/api/v1/user/coolmanager@example.com` (the matcher looks for `/api/v1/user/coolmanager%40example.com`).
Pin to the old requests-mock until this is sorted out upstream in https://github.com/jamielennox/requests-mock/issues/158

tox: pin to requests-mock 1.8.0

---

tests/integration/errata_tool_release/create-1.yml

As of RHELWF-1420, the ET REST API requires us to pass a product parameter for zstream releases.
Fixes: #197

release: set product on zstream in integration test

---

library/errata_tool_product_version.py
tests/test_errata_tool_product_version.py

A non-existent errata product should not cause the product version task
to fail when running in check mode. It could be that the product will be
created along with the product version. The task should not fail in this
case because it would be expected.

Avoid raising exception during check_mode query

---

.github/workflows/tests.yml

Update the title of this step, so it's clearer why we're fetching these branches.

github: fix title of branch fetch steps

---

tox.ini

requests-mock 1.9.2 has fixes quoting on paths, so we can unpin this now.
This reverts commit 58f46416841ade28f4b8266edd85973b0f8945cf.

Revert "tox: pin to requests-mock 1.8.0"

---

library/errata_tool_cdn_repo.py
library/errata_tool_release.py
library/errata_tool_variant.py
tests/fixtures/rhel-8.4.0.z+eus.release.json
tests/test_errata_tool_release.py

Don't manually assemble the GET request filter URL. Use requests' `params` kwarg so that we quote special characters - particularly the `+` character.
This fixes a bug where Ansible would load the wrong URLs for releases, variants, or CDN repos with `+` in names. When Ansible loaded URLs with unquoted `+` characters in the query strings, the ET web server interprets those as spaces, so it would return no results for those named resources. This led Ansible to incorrectly assume the resources did not exist, and Ansible would incorrectly try to create them.
The ET server permits users to create more than one release with the same name (RHELWF-3629), so Ansible could end up creating multiple releases on the server.

get resources with requests' params

---

tests/integration/errata_tool_cdn_repo/packages-1.yml
tests/integration/errata_tool_cdn_repo/variants-1.yml
tests/integration/errata_tool_release/create-1.yml
tests/integration/errata_tool_release/create-2.yml
tests/integration/errata_tool_release/product-versions-1.yml
tests/integration/main.yml.in

Prior to this PR, the integration tests did not pass on Python 3.
Add conditions for unicode strings on py2 vs py3, and rename the reserved `async` variable name.

tests: support Python 3 for integration tests

---

library/errata_tool_cdn_repo.py
library/errata_tool_product.py
library/errata_tool_product_version.py
library/errata_tool_release.py
library/errata_tool_variant.py
module_utils/common_errata_tool.py
tests/test_errata_tool_cdn_repo.py
tests/test_errata_tool_product.py

This allows using --diff to show a diff of the changes.
The motivation is related to showing human readable diff output in Honey Badger, but I think it should be generally useful for users of these modules.
Issue #207

Add diff output for most tasks

---

build-collection
meta/runtime.yml

Ansible Galaxy now requires all collections to have a `meta/runtime.yml` file with `requires_ansible`. I'm choosing `2` because most of the v2 releases should work.

add meta/runtime.yml

---

README.rst
library/errata_tool_product.py
tests/integration/errata_tool_product/create-1.yml
tests/test_errata_tool_product.py

The field was removed from the schema in CWFENGINE-381 because now
all text only advisories should require dists.
Keep it as an acceptible attribute so we don't break existing
playbooks, but ignore its value. It should be considered deprecated.
Issue: #211

Remove text_only_advisories_require_dists field

---

tests/integration/errata_tool_product/text-only-dists-1.yml

This field is deprecated and has no effect, but we want to make sure existing playbooks that define it will continue to work.

tests: exercise setting text_only_advisories_require_dists

---

library/errata_tool_product.py
library/errata_tool_release.py

The web UI only shows users with the `docs` role in the `default_docs_reviewer` dropdown, so the ET requires that role to be set on these users.
`program_manager` accounts do not require a specific role.

document default_docs_reviewer and program_manager role requirements

---

library/errata_tool_product.py

EXD_ORG_GROUPS.keys() is not a list. We need to use list() to convert it to list.
@ktdreyer @simonbaird  Can you help review it? I think it is better to do a test.

Use list in exd_org_group

---

requirements.txt

Ansible 5.0.0 requires Python 3.8. For Python 3.7 and older, pin to the latest Ansible 4 version.

requirements.txt: pin to Ansible 4 on old python versions

---

.github/workflows/tests.yml
tox.ini

Run unit tests with Python 3.9.

add py39 to tox tests

---

.mergify.yml

GitHub does this automatically now, faster than Mergify can do it. Remove this setting to avoid Mergify showing errors when trying to delete non-existent branches.

mergify: remove "delete branch" setting

---

.mergify.yml

The old configuration is deprecated, https://blog.mergify.com/strict-mode-deprecation/

mergify: use queues instead of strict mode

---

.github/workflows/integration.yml

This commit introduces no functional change. It just re-organizes the settings to make room to add more OSes (eg. rhel-8) in the future.

github: add matrix "os" parameter for integration tests

---

tests/integration/errata_tool_cdn_repo/packages-1.yml

From CWFENGINE-471 and CWFENGINE-524, every new CdnRepoPackage mapping comes with a new tag format.
See the `DEFAULT_TAG_TEMPLATES` constant in errata-rails.git.
Update the integraion test that identifies how many default tags we remove in order to account for this new feature.

tests: handle new {{hotfix}}-{{advisory}} container tags

---

tests/README.rst
tests/utils.py

Document the fake `exit_json()` and `fail_json()` methods in `tests/utils.py`.

tests: document exit_json() and fail_json() fakes

---

.github/workflows/ansiblegalaxy.yml
.github/workflows/tests.yml
.mergify.yml

The `ubuntu-latest` image no longer has `py27` or `py36` available. Pin to an older Ubuntu image for testing these older Python versions.
Update to the latest `checkout` and `setup-python` actions.
Require `py39` to pass before auto-merging with Mergify.

Fix and improve GitHub Actions tests

---

README.rst
library/errata_tool_product.py
library/errata_tool_release.py
tests/test_errata_tool_product.py
tests/test_errata_tool_release.py

errata-tool-ansible can configure products and releases with disabled user accounts. This does not always match what a human release engineer would do manually in the web UI.
Update `errata_tool_product` and `errata_tool_release` modules to show an error in check mode when the user accounts are not enabled and `ANSIBLE_STRICT_USER_CHECK_MODE` is set.
EDIT: old approach, not used: ~Prior to this change, errata-tool-ansible could configure products and releases with disabled user accounts. Update `common_errata.get_user()` with an additional check to verify that the user account is not disabled.~
See https://issues.redhat.com/browse/CWFCONF-3328 for this feature request.

verify users are enabled in strict check mode

---

.stickler.yml

It's annoying to coerce lines to be 79 characters. Bump this up a bit.

.stickler.yml: max-line-length 120

---

library/errata_tool_release.py

These fields are unsupported, so we should not display them in a diff.

release: hide is_silent and notify_bugzilla in diff

---

library/errata_tool_cdn_repo.py
library/errata_tool_product_version.py
library/errata_tool_release.py
library/errata_tool_user.py
library/errata_tool_variant.py
module_utils/common_errata_tool.py
tests/test_errata_tool_cdn_repo.py
tests/test_errata_tool_release.py

Includes API request details when an unexpected status code is encountered.
Makes error consistent across all API calls.
Also fixes problem when error response from the API contains "errors" field instead of "error" or does not contain any of these.

Make errors from Errata Tool API more verbose

---

library/errata_tool_release.py
tests/test_errata_tool_release.py

Fixes the following error:
...
File .../errata_tool_ansible/plugins/module_utils/common_errata_tool.py, line 208, in diff_settings
TypeError: unhashable type: 'dict'
This is caused the fact that brew_tags passed to the module is simple list of names, but the object returned by release API is in the following form:
"relationships": {
"brew_tags": [
{"id": 100, "name": "rhel-x.y-z-candidate"},
{"id": 101, "name": "rhel-x.y-z-nocompose-candidate"},
],
...
}

Fix showing diff for release brew_tags

---

.github/workflows/tests.yml

GitHub no longer supports running Python 2.7 natively.

github: drop py27 matrix entry

---

tests/integration/errata_tool_product_version/create-2.yml

Re-add the parameters we dropped from the integration tests in https://github.com/ktdreyer/errata-tool-ansible/pull/291. 
These are no-ops now, but this test ensures that we will not crash when older playbooks specify these parameters.

tests: re-add use_quay_for_containers parameters

---

library/errata_tool_product_version.py
module_utils/common_errata_tool.py
tests/test_errata_tool_product.py
tests/test_errata_tool_release.py

Avoids showing confusing diffs for lists/arrays. For example:
--- before: Original product 'Test-product'
+++ after: Modified product 'Test-product'
@@ -1,24 +1,22 @@
...
push_targets:
- ftp
+- cdn
- cdn_stage
-- cdn
short_name: Test-product
...
This assumes that all list attributes do not depend on item order and cannot contain duplicate items.

Fix showing diffs for lists

---

README.rst

Ansible Galaxy no longer supports the v2 REST API. Switch to v3.

README: update Galaxy badge URL

---

library/errata_tool_product_version.py
tests/integration/errata_tool_cdn_repo/packages-1.yml
tests/integration/errata_tool_product_version/ima-sig-key-1.yml
tests/integration/errata_tool_product_version/ima-sig-key-2.yml
tests/test_errata_tool_product_version.py

A couple of fixes for the CI, and a followup to https://github.com/ktdreyer/errata-tool-ansible/pull/309:
1. Fix the integration tests to handle the addition of `prerelease-{{advisory}}` to `DEFAULT_TAG_TEMPLATES` from CWFCONF-5454.
2. Remove `type='str'` from the module's argument_spec, since this is Ansible's default behavior already.
3. When creating a new Product Version without `ima_sig_key_name`, don't send any `ima_sig_key_name` value to the server. (This fixes a crash in the integration tests. For some reason the server responded with a HTTP 500 error.)
4. Add new integration tests for setting `ima_sig_key_name` on new and existing Product Versions.

ima_sig_key fixes

---

.mergify.yml

I've dropped the py27 tests in GitHub Actions in https://github.com/ktdreyer/errata-tool-ansible/pull/287

mergify: remove py27 requirement

---

tests/integration/errata_tool_cdn_repo/packages-1.yml

On RHEL 7 the messages are ordered this way, but on a RHEL 8 host they are not. Rather than test the order of the messages, simply assert that they're all present.

tests: flexible ordering for cdn pkg tag removal messages

---

README.rst

On RHEL, the latest ansible-core requires Python 3.11. Explain how to enable [the Copr repository](https://copr.fedorainfracloud.org/coprs/ktdreyer/python3.11/) that has the dependency packages.

README: document python 3.11 copr for RHEL

---

.github/workflows/integration.yml
.mergify.yml
README.rst
library/errata_tool_cdn_repo.py
tests/integration/errata_tool_cdn_repo/create-2.yml
tests/integration/errata_tool_cdn_repo/packages-1.yml
tests/integration/errata_tool_cdn_repo/variants-1.yml
tests/test_errata_tool_cdn_repo.py

- I can't get `docker-compose` to work on RHEL 7, and the ET developers  prefer `podman-compose` (RHELWF-10345).
- The path to `rake` has changed in newer ET versions. Update the GH Action for this.
- We can't use Pulp-style repo names any more (#320)
Fixes: #320

integration test fixes (drop el7, new docker repo names)

---

library/errata_tool_variant.py

The tps stream field or determining tps stream for a variant is deprecated once https://issues.redhat.com/browse/RHELWF-8494 is merged. So this mandatory require TPS stream for variant logic is not applicable.

removed requiring tps steam logic from variant creation step
