library/errata_tool_product.py

This ERRATA ticket is resolved.
Document the method parameters and return value instead.

product: improve get_product docstring

---

.travis.yml

Reduce the boilerplate copy & paste.

.travis.yml: simplify configuration

---

.travis.yml

This fixes a regression in 3cb8a66c591f8129602f2629c03a3ee9fca1457d ".travis.yml: simplify configuration"

.travis.yml: install coveralls before using it

---

library/errata_tool_product_version.py

Nothing uses this method. Remove it.

product_version: remove diff_product_version()

---

library/errata_tool_variant.py

This docstring was a bit too hard to read.

variant: wrap docstring at 80 chars

---

tests/fixtures/8Base-RHCEPH-4.0-Tools.variant.json
tests/fixtures/8Base.variant.json
tests/test_errata_tool_variant.py
tests/utils.py

Add test coverage for most of `errata_tool_variant.py`.

tests: add unit tests for errata_tool_variant methods

---

library/errata_tool_variant.py

Keep these lines within 80 characters

variant: shorten scraper variable

---

library/errata_tool_variant.py
tests/fixtures/8Base-RHCEPH-4.0-Tools.variant.json
tests/test_errata_tool_variant.py

This new REST API for variants is now live in production, so we can use it.
Fixes: #45

variant: use new API

---

tests/test_errata_tool_user.py

Verify that we are sending the expected JSON body in our HTTP request for `POST /api/v1/user`.

tests: assert JSON body for create_user()

---

.github/workflows/ansiblegalaxy.yml
.travis.yml
README.rst
build-collection
galaxy.yml
tests/integration/collection.sh

Add the packaging and CI scripts for uploading to Ansible Galaxy.

add Ansible Collection packaging

---

library/errata_tool_variant.py

Variant without rhel_variant is marked as rhel_variant. `tps_stream` has
to be defined when rhel_variant is not defined.
Fixes #76

Allow to create variant without rhel_variant

---

README.rst
library/errata_tool_request.py
module_utils/common_errata_tool.py
tests/test_errata_tool_request.py

This module is helpful for integration testing.
Fixes: #24

add errata_tool_request module

---

tests/test_errata_tool_user.py

Add test coverage for the `edit_user()` method.

user: add unit test for edit_user()

---

tests/test_errata_tool_user.py

Add test coverage for the `ensure_user()` method.

user: add unit tests for ensure_user()

---

.github/workflows/integration.yml
tests/integration/errata_tool_product/create-1.yml
tests/integration/errata_tool_product/main.yml
tests/integration/errata_tool_user/create-1.yml
tests/integration/errata_tool_user/create-2.yml
tests/integration/errata_tool_user/main.yml
tests/integration/errata_tool_variant/create-1.yml
tests/integration/errata_tool_variant/create-2.yml
tests/integration/errata_tool_variant/main.yml
tests/integration/main.yml.in
tests/integration/run.sh

Run a series of playbooks against a throwaway ET server instance using a GitHub self-hosted runner.
Fixes: #88

add integration tests

---

library/errata_tool_release.py

Document the expected parameters for the `api_data()` method.

release: document api_data() parameters

---

tests/fixtures/workflow_rules.html
tests/test_common_errata_tool.py
tests/utils.py

Add unit test coverage for the `WorkflowRulesScraper` class.

common: add unit tests for WorkflowRulesScraper

---

library/errata_tool_release.py
tests/test_errata_tool_release.py

and update the inline documentation
Fixes: #94

release: support pelc_product_version_name parameter

---

library/errata_tool_cdn_repo.py

Give an example of listing multiple variants on a CDN repo.
Explain that Ansible will add or remove any variants according to the list that the user specifies for this parameter.

cdn_repo: more docs for variants parameter

---

library/errata_tool_product.py

Shorten and break up the code so that the lines wrap at 80 characters to satisfy Stickler CI and flake8.

product: wrap lines at 80 characters

---

library/errata_tool_release.py

Shorten and break up the code so that the lines wrap at 80 characters to satisfy Stickler CI and flake8.

release: wrap lines at 80 characters

---

library/errata_tool_product.py
tests/integration/errata_tool_product/create-1.yml
tests/test_errata_tool_product.py

Support reading and setting the EXD org group.

Support reading and setting EXD org groups for products

---

tests/integration/errata_tool_product/exd-org-group-1.yml

Exercise setting (or not setting) the `exd_org_group` parameter for products.

product: add integration tests for exd_org_group

---

tests/test_errata_tool_release.py

Add unit tests for the `ensure_release()` method.

release: test ensure_release() method

---

library/errata_tool_user.py

Document the behavior of the "organization" parameter

user: document "organization" behavior

---

tests/test_errata_tool_user.py

Add a unit test to cover the `main()` method in `errata_tool_user.py`.

user: test main() method

---

tests/integration/errata_tool_cdn_repo/create-1.yml
tests/integration/errata_tool_cdn_repo/create-2.yml
tests/integration/errata_tool_cdn_repo/main.yml

Test creating RPM and Docker CDN repositories.

cdn_repo: add creation integration tests

---

tests/integration/errata_tool_cdn_repo/variants-1.yml

Exercise adding and removing a variant from a CDN repo.

cdn_repo: add integration tests for variants

---

tests/integration/errata_tool_cdn_repo/packages-1.yml

Exercise adding, editing, and removing a container package from a CDN repo.

cdn_repo: add integration tests for packages

---

tests/integration/errata_tool_product_version/create-1.yml
tests/integration/errata_tool_product_version/main.yml
tests/integration/errata_tool_product_version/no-product-1.yml

Test creating a Product Version and asserting its attributes and relationships.
Test creating a PV with a non-existent product in check mode and non-check mode. check mode should pass, and non-check mode should fail with a 404 error.

product_version: add integration tests

---

library/errata_tool_variant.py

Expand the explanations about the `rhel_variant` parameter.

variant: improve documentation for rhel_variant

---

README.rst

Explain how to set the `REQUESTS_CA_BUNDLE` environment variable.

README: explain RH IT CA and REQUESTS_CA_BUNDLE

---

.mergify.yml

Lukas is a trusted code author

mergify: auto-merge PRs from hluk

---

library/errata_tool_product_version.py
tests/integration/errata_tool_product_version/create-1.yml
tests/integration/errata_tool_product_version/create-2.yml

This is no longer an attribute of product versions, so we should remove the ability to configure this.
JIRA: CWFCONF-4867

Remove use_quay_for_containers_stage

---

module_utils/common_errata_tool.py
tests/test_errata_tool_release.py

Fix showing non-json errors

---

README.rst
library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

Fixes https://github.com/ktdreyer/errata-tool-ansible/issues/299

Add external_name parameter as editable field

---

README.rst
library/errata_tool_product.py
tests/integration/errata_tool_product/create-1.yml
tests/test_errata_tool_product.py

This value has been added to HoneyBadger but it recently failed since it's not available in the module yet.
JIRA: CWFCONF-5408

Add show_bug_package_mismatch_warning as editable field

---

README.rst
library/errata_tool_product.py
library/errata_tool_product_version.py
tests/integration/errata_tool_product/create-1.yml
tests/integration/errata_tool_product_version/create-1.yml
tests/integration/errata_tool_product_version/create-2.yml
tests/test_errata_tool_product.py
tests/test_errata_tool_product_version.py

Add the `suppress_push_request_jira` field for:
- product
- product_version
JIRA: CWFCONF-5478

Add suppress_push_request_jira as editable field

---

library/errata_tool_product.py

Document that the ET server requires that each "name" must be unique.
Fixes: #202

product: document that name must be unique

---

.github/workflows/integration.yml
.mergify.yml

Test on RHEL 8 as well as RHEL 7.

github: add rhel-8 integration tests

---

library/errata_tool_cdn_repo.py
tests/test_errata_tool_cdn_repo.py

Fixes: https://github.com/ktdreyer/errata-tool-ansible/issues/261

feat(CWFCONF-3703): Add support for hotfix and prerelease tags

---

README.rst
library/errata_tool_product_version.py
tests/integration/errata_tool_product_version/create-1.yml
tests/integration/errata_tool_product_version/create-2.yml
tests/test_errata_tool_product_version.py

Fixes: #259
JIRA: CWFCONF-8260

Feat(CWFCONF-8260): Add allow_unreleased_rpms for product_versions

---

.mergify.yml

Bryan is a trusted code author

mergify: auto-merge PRs from CryptoRodeo

---

README.rst
library/errata_tool_rhel_release.py
tests/fixtures/rhel-2.1.rhel_release.json
tests/fixtures/rhel-8.1.0.z.main+eus.rhel_release.json
tests/integration/errata_tool_rhel_release/create-1.yml
tests/integration/errata_tool_rhel_release/main.yml
tests/test_errata_tool_rhel_release.py

Fixes: #173
JIRA: CWFCONF-8282

Add module for creating RHEL releases

---

README.rst
library/errata_tool_product_version.py
tests/test_errata_tool_product_version.py

Add container_sig_key_name as param for PVs

---

README.rst
library/errata_tool_release.py
tests/fixtures/rhceph-4.0.release.json
tests/fixtures/rhel-8.4.0.z+eus.release.json
tests/test_errata_tool_release.py

https://github.com/ktdreyer/errata-tool-ansible/issues/265

Add the release support for `is_silent` parameter
